
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "John",
    "surname": "Smith",
    "birthday": "2022-02-28",
    "email": "testww1@@example.com",
    "password": "test12345"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testww1@example",
    "password": "test12345"
}

